targets:
  $default:
    builders:
      windows_event_log_generator|windows_event_log:
        enabled: true

builders:
  windows_event_log:
    import: "package:windows_event_log_generator/builder.dart"
    builder_factories: ["windowsEventLogBuilder"]
    build_extensions: { ".dart": [".eventlog.g.part"] }
    build_to: cache
    auto_apply: dependents
    # To copy the `.g.part` content into `.g.dart` in the source tree
    applies_builders: ["source_gen:combining_builder"]
    defaults:
      options:
          messageCompilerPath: 'C:\Program Files (x86)\Windows Kits\10\bin\10.0.22000.0\x64\mc.exe'